version: '3.3'
services: 
    db:
        container_name: dev-mysql
        image: jnsousa/mysql8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo 
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306
             