version: '3.1'
services: 
    db:
        container_name: dev-postgres
        image: jnsousa/postgres:12.8
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            POSTGRES_PASSWORD: docker
        ports: 
            - 5432:5432